'use strict';
const REGULAMENTO_OFICIAL='https://bio.ufpr.br/biomedicina/wp-content/uploads/sites/4/2026/10/PROGRAMA-DE-ORIENTACAO-ACADEMICA.pdf';
const $=id=>document.getElementById(id);
function setText(id,value){if($(id)&&typeof value==='string')$(id).textContent=value;}
function setLink(id,url,label){const a=$(id);if(!a||!url)return;try{const u=new URL(url,location.href);if(!['https:','http:'].includes(u.protocol))return;a.href=u.href;if(label)a.textContent=label;a.target='_blank';a.rel='noopener noreferrer';}catch(e){console.warn('Link inválido',id,e);}}
function make(tag,cls,txt){const el=document.createElement(tag);if(cls)el.className=cls;if(txt)el.textContent=txt;return el;}
function cards(id,items){const parent=$(id);if(!parent||!Array.isArray(items))return;parent.replaceChildren();items.forEach(item=>{const card=make('article','card');card.append(make('h3','',item.titulo||''),make('p','',item.descricao||''));parent.append(card);});}
function render(d){setText('hero-eyebrow',d.hero?.sobretitulo);setText('hero-title',d.hero?.titulo);setText('hero-lead',d.hero?.chamada);setText('hero-description',d.hero?.descricao);setText('reg-title',d.regulamento?.titulo);setText('reg-description',d.regulamento?.descricao);setText('reg-note',d.regulamento?.observacao);/* Link oficial fixo: não depende de configuração JSON */setLink('reg-link',REGULAMENTO_OFICIAL,(d.regulamento?.textoBotao||'Acessar regulamento completo (PDF)')+' ↗');setText('sobre-title',d.sobre?.titulo);if(Array.isArray(d.sobre?.paragrafos)){const root=$('sobre-text');root.replaceChildren();d.sobre.paragrafos.forEach(t=>root.append(make('p','',t)));}cards('objetivos-list',d.objetivos);setText('func-title',d.funcionamento?.titulo);cards('etapas-list',d.funcionamento?.etapas);setText('orient-title',d.orientacao?.titulo);setText('orient-text',d.orientacao?.descricao);setLink('orient-link',d.orientacao?.url,(d.orientacao?.textoBotao||'Site da Coordenação')+' ↗');if(Array.isArray(d.documentos)){const root=$('documentos-list');root.replaceChildren();d.documentos.forEach(item=>{const box=make('div','doc');const a=make('a','',item.titulo+' ↗');a.href=REGULAMENTO_OFICIAL;a.target='_blank';a.rel='noopener noreferrer';box.append(a,make('p','small',item.descricao||''));root.append(box);});}if(Array.isArray(d.faq)){const root=$('faq-list');root.replaceChildren();d.faq.forEach(item=>{const detail=make('details','faq');detail.append(make('summary','',item.pergunta),make('p','',item.resposta));root.append(detail);});}setText('version',d.meta?.versao?'Versão '+d.meta.versao+' · Atualização '+(d.meta.atualizacao||''):'');}
async function init(){try{const response=await fetch('./dados.json',{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);render(await response.json());}catch(err){console.warn('Não foi possível carregar dados.json; conteúdo essencial e regulamento permanecem disponíveis.',err);const message=make('p','small','Algumas informações complementares estão temporariamente indisponíveis. O regulamento oficial permanece acessível acima.');$('faq-list')?.append(message);}}
init();
