"use strict";
const $ = (selector) => document.querySelector(selector);
function el(tag, className, text) { const node = document.createElement(tag); if(className) node.className = className; if(text !== undefined) node.textContent = text; return node; }
function addText(parent, tag, text, className) { const node=el(tag,className,text); parent.append(node); return node; }
function section(parent,id,content,band=false){ const outer=el('section',band?'band':''); outer.id=id; const inner=el('div','wrap section'); outer.append(inner);parent.append(outer);if(content.etiqueta)addText(inner,'p',content.etiqueta,'kicker');addText(inner,'h2',content.titulo);return inner;}
function paragraphs(parent,arr){for(const t of arr||[])addText(parent,'p',t);}
function validUrl(value){try{const u=new URL(value,location.href);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function action(parent,data){if(!data)return;const href=data.url?validUrl(data.url):data.destino;if(!href)return;const a=el('a','button',data.texto+' ↗');a.href=href;if(data.url){a.target='_blank';a.rel='noopener noreferrer';}parent.append(a);}
function render(d){document.title=d.meta.titulo+' | Biomedicina UFPR';$('#hero-kicker').textContent=d.hero.sobretitulo;$('#hero-title').textContent=d.hero.titulo;$('#hero-lead').textContent=d.hero.chamada;$('#hero-desc').textContent=d.hero.descricao;const hb=$('#hero-button');hb.textContent=d.hero.botao.texto+' ↗';hb.href=d.hero.botao.destino;
const root=$('#content');root.replaceChildren();let s=section(root,'sobre',d.introducao);paragraphs(s,d.introducao.paragrafos);
s=section(root,'beneficios',d.beneficios,true);const cards=el('div','grid');s.append(cards);d.beneficios.itens.forEach((item,i)=>{const c=el('article','card');addText(c,'span',String(i+1).padStart(2,'0'),'num');addText(c,'h3',item.titulo);addText(c,'p',item.texto);cards.append(c);});
const split=el('section','wrap section split');split.id='publico';root.append(split);const left=el('div');split.append(left);addText(left,'p',d.publico.etiqueta,'kicker');addText(left,'h2',d.publico.titulo);paragraphs(left,d.publico.paragrafos);const right=el('div','panel');split.append(right);addText(right,'p',d.funcionamento.etiqueta,'kicker');addText(right,'h2',d.funcionamento.titulo);addText(right,'p',d.funcionamento.descricao);
s=section(root,'funcionamento',{titulo:'Etapas do acompanhamento',etiqueta:'Como acontece'},true);const steps=el('div','steps');s.append(steps);d.funcionamento.passos.forEach((item)=>{const st=el('article','step');addText(st,'h3',item.titulo);addText(st,'p',item.texto);steps.append(st);});addText(s,'p',d.funcionamento.observacao,'notice');
s=section(root,'diferenciais',d.diferenciais);const ul=el('ul','feature-list');s.append(ul);d.diferenciais.itens.forEach(t=>addText(ul,'li',t));
s=section(root,'comissao',d.comissao,true);addText(s,'p',d.comissao.descricao);if(d.comissao.integrantes?.length){const list=el('ul');s.append(list);d.comissao.integrantes.forEach(t=>addText(list,'li',t));}addText(s,'p',d.comissao.aviso,'notice');
s=section(root,'orientacao',d.orientacao);const cta=el('div','cta');s.append(cta);addText(cta,'p',d.orientacao.descricao);action(cta,d.orientacao.botao);addText(cta,'p',d.orientacao.nota,'muted');
s=section(root,'documentos',d.documentos,true);addText(s,'p',d.documentos.descricao);if(d.documentos.itens?.length){const list=el('ul','doc-list');s.append(list);d.documentos.itens.forEach(item=>{const li=el('li');const u=validUrl(item.url);if(u){const a=el('a','',item.titulo);a.href=u;a.target='_blank';a.rel='noopener noreferrer';li.append(a);}else{li.textContent=item.titulo;}list.append(li);});}addText(s,'p',d.documentos.aviso,'notice');
s=section(root,'faq',d.faq);d.faq.itens.forEach(item=>{const details=el('details');addText(details,'summary',item.pergunta);addText(details,'p',item.resposta);s.append(details);});}
fetch('dados.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(render).catch(err=>{const root=$('#content');root.replaceChildren();const s=el('section','wrap section');addText(s,'h2','Não foi possível carregar o conteúdo.');addText(s,'p','Confirme que dados.json está na mesma pasta que index.html e que a página foi aberta via GitHub Pages ou servidor HTTP.');root.append(s);console.error('Erro ao carregar dados.json:',err);});
